import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useMemo, useState } from 'react';
import { AlertTriangle, BadgeCheck, Briefcase, LineChart, Newspaper, Radio, RefreshCcw, Users, } from 'lucide-react';
import { Button } from './ui/button';
import { useSessionContext } from '../context/session';
import { cn, formatCompactNumber, formatCurrency, formatPercent, formatRelativeTime, } from '@/lib/utils';
import { useMarketData } from '@/hooks/useMarketData';
import { useNewsFeed } from '@/hooks/useNewsFeed';
import { useJobListings } from '@/hooks/useJobListings';
import { useCommunities } from '@/hooks/useCommunities';
import { useCertificates } from '@/hooks/useCertificates';
const tabs = [
    { id: 'markets', label: 'Markets', icon: LineChart },
    { id: 'news', label: 'Newswire', icon: Newspaper },
    { id: 'jobsea', label: 'JobSea', icon: Briefcase },
    { id: 'communities', label: 'Communities', icon: Users },
    { id: 'certificates', label: 'Certificates', icon: BadgeCheck },
    { id: 'tv', label: 'Live Feeds', icon: Radio },
];
function TerminalDashboard() {
    const { session, logout, showLogin, loginWithLinkedInDemo, isAuthenticating } = useSessionContext();
    const [activeTab, setActiveTab] = useState('markets');
    const market = useMarketData();
    const news = useNewsFeed();
    const jobs = useJobListings();
    const communities = useCommunities();
    const certificates = useCertificates();
    const welcome = useMemo(() => {
        if (!session) {
            return 'Markets overview';
        }
        const first = session.name.trim().split(' ')[0] || session.name;
        return `${first}, your console is live`;
    }, [session]);
    return (_jsxs("section", { className: "space-y-6", children: [_jsxs("header", { className: "flex flex-col gap-2", children: [_jsx("span", { className: "text-xs uppercase tracking-[0.45em] text-terminal-green/70", children: "Financegram Terminal - Connected" }), _jsx("h2", { className: "text-3xl text-terminal-green", children: welcome }), _jsx("p", { className: "text-sm text-terminal-green/60", children: "Financegram pipes first-party data, market trades, newsroom copy, hiring flow, and credential pathways into a Bloomberg-inspired surface tuned for fast decision making." }), _jsxs("div", { className: "flex flex-wrap items-center gap-4 text-[11px] uppercase tracking-[0.3em] text-terminal-green/45", children: [_jsxs("span", { children: ["Market feed: ", market.lastUpdated ? `synced ${formatRelativeTime(market.lastUpdated)}` : 'warming up'] }), _jsxs("span", { children: ["Newswire: ", news.sourceLabel] }), _jsxs("span", { children: ["JobSea: ", jobs.lastUpdated ? `refreshed ${formatRelativeTime(jobs.lastUpdated)}` : 'initializing'] })] })] }), _jsx("nav", { className: "flex flex-wrap gap-2", children: tabs.map(({ id, label, icon: Icon }) => {
                    const isActive = activeTab === id;
                    return (_jsxs("button", { type: "button", onClick: () => setActiveTab(id), className: cn('flex items-center gap-2 rounded-lg border px-4 py-2 text-xs uppercase tracking-[0.25em] transition', isActive
                            ? 'border-terminal-green/80 bg-terminal-green/10 text-terminal-green'
                            : 'border-terminal-green/25 bg-black/60 text-terminal-green/60 hover:border-terminal-green/60 hover:text-terminal-green'), children: [_jsx(Icon, { className: "h-4 w-4" }), label] }, id));
                }) }), _jsxs("div", { className: "grid gap-6 xl:grid-cols-[2fr,1fr]", children: [_jsxs("div", { className: "space-y-6", children: [activeTab === 'markets' && _jsx(MarketsPanel, { data: market }), activeTab === 'news' && _jsx(NewsPanel, { news: news }), activeTab === 'jobsea' && _jsx(JobSeaPanel, { jobs: jobs }), activeTab === 'communities' && (_jsx(CommunitiesPanel, { communities: communities, memberships: session?.communities ?? [] })), activeTab === 'certificates' && _jsx(CertificatesPanel, { certificates: certificates }), activeTab === 'tv' && _jsx(TvPanel, {})] }), _jsxs("aside", { className: "space-y-6", children: [_jsx(MarketPulseCard, { data: market }), _jsx(HeadlineTicker, { news: news }), _jsx(SessionCard, { session: session, onLogout: logout, onLogin: showLogin, onDemo: loginWithLinkedInDemo, isAuthenticating: isAuthenticating })] })] })] }));
}
function MarketsPanel({ data }) {
    const { quotes, series, isLoading, error, lastUpdated } = data;
    const currentSeriesValue = series.at(-1)?.value;
    return (_jsxs("div", { className: "rounded-2xl border border-terminal-green/30 bg-black/70 p-6 shadow-[inset_0_0_35px_rgba(74,255,128,0.08)]", children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-3", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-sm uppercase tracking-[0.35em] text-terminal-green", children: "Market grid" }), _jsx("p", { className: "text-xs text-terminal-green/50", children: "Live index composite sourced from Financegram\uFFFDs market core." })] }), _jsxs("div", { className: "flex items-center gap-2 text-xs text-terminal-green/50", children: [_jsx(RefreshCcw, { className: cn('h-4 w-4', isLoading ? 'animate-spin' : 'opacity-50') }), lastUpdated ? `Updated ${formatRelativeTime(lastUpdated)}` : 'Awaiting first tick'] })] }), error ? (_jsxs("div", { className: "mt-4 flex items-center gap-3 rounded-lg border border-terminal-green/40 bg-terminal-green/10 p-3 text-xs text-amber-300", children: [_jsx(AlertTriangle, { className: "h-4 w-4" }), _jsx("span", { children: error })] })) : null, _jsxs("div", { className: "mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3", children: [isLoading && quotes.length === 0 ? (_jsx("div", { className: "col-span-full grid h-32 place-items-center text-xs uppercase tracking-[0.3em] text-terminal-green/50", children: "Streaming..." })) : null, quotes.map((quote) => {
                        const changeClass = quote.change >= 0 ? 'text-terminal-green' : 'text-rose-400';
                        const delta = formatPercent(quote.changePercent);
                        return (_jsxs("div", { className: "rounded-xl border border-terminal-green/40 bg-black/70 p-4 shadow-[0_0_25px_rgba(74,255,128,0.08)]", children: [_jsxs("div", { className: "flex items-center justify-between text-[11px] uppercase tracking-[0.3em] text-terminal-green/60", children: [_jsx("span", { children: quote.symbol }), _jsx("span", { children: quote.label })] }), _jsxs("div", { className: "mt-3 flex items-end justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-3xl text-terminal-green", children: formatCurrency(quote.price) }), _jsxs("p", { className: "text-xs text-terminal-green/40", children: ["Prev ", formatCurrency(quote.previousClose)] })] }), _jsxs("div", { className: "text-right", children: [_jsx("span", { className: cn('text-lg font-medium', changeClass), children: delta }), _jsxs("p", { className: "text-xs text-terminal-green/40", children: ["? ", formatCurrency(quote.change)] })] })] })] }, quote.symbol));
                    })] }), _jsxs("div", { className: "mt-6 rounded-xl border border-terminal-green/30 bg-black/60 p-4", children: [_jsxs("div", { className: "flex items-center justify-between text-[11px] uppercase tracking-[0.3em] text-terminal-green/50", children: [_jsx("span", { children: "Intraday trace" }), _jsx("span", { children: currentSeriesValue ? formatCurrency(currentSeriesValue) : 'no feed' })] }), _jsx(MarketSparkline, { data: series })] })] }));
}
function MarketSparkline({ data }) {
    if (!data.length) {
        return (_jsx("div", { className: "grid h-40 place-items-center text-xs uppercase tracking-[0.3em] text-terminal-green/40", children: "Feed inactive" }));
    }
    const width = 720;
    const height = 200;
    const values = data.map((point) => point.value);
    const max = Math.max(...values);
    const min = Math.min(...values);
    const range = max - min || 1;
    const points = data
        .map((point, index) => {
        const x = (index / (data.length - 1 || 1)) * width;
        const y = height - ((point.value - min) / range) * height;
        return `${x},${y}`;
    })
        .join(' ');
    const areaPoints = `0,${height} ${points} ${width},${height}`;
    return (_jsxs("svg", { viewBox: `0 0 ${width} ${height}`, preserveAspectRatio: "none", className: "mt-4 h-48 w-full rounded-lg border border-terminal-green/20 bg-[rgba(16,40,22,0.35)]", children: [_jsxs("defs", { children: [_jsxs("linearGradient", { id: "sparklineStroke", x1: "0", x2: "0", y1: "0", y2: height, gradientUnits: "userSpaceOnUse", children: [_jsx("stop", { offset: "0%", stopColor: "#8dff9f", stopOpacity: "0.95" }), _jsx("stop", { offset: "100%", stopColor: "#4bff77", stopOpacity: "0.4" })] }), _jsxs("linearGradient", { id: "sparklineFill", x1: "0", x2: "0", y1: "0", y2: height, gradientUnits: "userSpaceOnUse", children: [_jsx("stop", { offset: "0%", stopColor: "rgba(77,255,131,0.35)" }), _jsx("stop", { offset: "100%", stopColor: "rgba(77,255,131,0.02)" })] })] }), _jsx("polyline", { points: areaPoints, fill: "url(#sparklineFill)", stroke: "none" }), _jsx("polyline", { points: points, fill: "none", stroke: "url(#sparklineStroke)", strokeWidth: 3, strokeLinejoin: "round", strokeLinecap: "round" })] }));
}
function NewsPanel({ news }) {
    const { items, isLoading, error, sourceLabel, lastUpdated } = news;
    return (_jsxs("div", { className: "rounded-2xl border border-terminal-green/30 bg-black/70 p-6", children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-3", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-sm uppercase tracking-[0.35em] text-terminal-green", children: "Newswire" }), _jsx("p", { className: "text-xs text-terminal-green/50", children: sourceLabel })] }), _jsx("span", { className: "text-[11px] uppercase tracking-[0.3em] text-terminal-green/40", children: lastUpdated ? `Updated ${formatRelativeTime(lastUpdated)}` : isLoading ? 'Refreshing feed�' : `${items.length} headlines` })] }), error ? (_jsxs("div", { className: "mt-4 flex items-center gap-3 rounded-lg border border-terminal-green/40 bg-terminal-green/10 p-3 text-xs text-amber-300", children: [_jsx(AlertTriangle, { className: "h-4 w-4" }), _jsx("span", { children: error })] })) : null, _jsxs("div", { className: "mt-6 grid gap-4 lg:grid-cols-2", children: [isLoading && items.length === 0 ? (_jsx("div", { className: "col-span-full grid h-40 place-items-center text-xs uppercase tracking-[0.3em] text-terminal-green/50", children: "Loading headlines\uFFFD" })) : null, items.slice(0, 8).map((story) => (_jsxs("article", { className: "group flex gap-4 rounded-xl border border-terminal-green/30 bg-black/60 p-4 transition hover:border-terminal-green/60 hover:bg-black/70", children: [_jsx("div", { className: "h-16 w-16 overflow-hidden rounded border border-terminal-green/30 bg-terminal-green/10", children: story.imageUrl ? (_jsx("img", { src: story.imageUrl, alt: story.title, className: "h-full w-full object-cover transition duration-500 group-hover:scale-105", loading: "lazy" })) : (_jsx("div", { className: "grid h-full w-full place-items-center text-[10px] uppercase tracking-[0.3em] text-terminal-green/40", children: "no art" })) }), _jsxs("div", { className: "flex-1 space-y-2", children: [_jsx("a", { href: story.url, target: "_blank", rel: "noreferrer", className: "text-sm font-medium text-terminal-green hover:text-terminal-green/80", children: story.title }), _jsxs("p", { className: "text-xs text-terminal-green/50", children: [story.source, " - ", story.publishedAt ? formatRelativeTime(story.publishedAt) : 'just in'] }), story.description ? (_jsx("p", { className: "text-xs text-terminal-green/40 line-clamp-2", children: story.description })) : null] })] }, story.id)))] })] }));
}
function JobSeaPanel({ jobs }) {
    const { listings, isLoading, error, lastUpdated } = jobs;
    return (_jsxs("div", { className: "rounded-2xl border border-terminal-green/30 bg-black/70 p-6", children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-3", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-sm uppercase tracking-[0.35em] text-terminal-green", children: "JobSea \uFFFD buy-side & fintech" }), _jsx("p", { className: "text-xs text-terminal-green/50", children: "Real-time requisitions piped from Financegram Talent Cloud." })] }), _jsx("div", { className: "text-[11px] uppercase tracking-[0.3em] text-terminal-green/40", children: lastUpdated ? `Synced ${formatRelativeTime(lastUpdated)}` : isLoading ? 'Syncing...' : `${listings.length} roles` })] }), error ? (_jsxs("div", { className: "mt-4 flex items-center gap-3 rounded-lg border border-terminal-green/40 bg-terminal-green/10 p-3 text-xs text-amber-300", children: [_jsx(AlertTriangle, { className: "h-4 w-4" }), _jsx("span", { children: error })] })) : null, _jsx("div", { className: "mt-4 overflow-hidden rounded-xl border border-terminal-green/30", children: _jsxs("table", { className: "min-w-full divide-y divide-terminal-green/20 text-sm", children: [_jsx("thead", { className: "bg-terminal-green/10 text-[11px] uppercase tracking-[0.3em] text-terminal-green/70", children: _jsxs("tr", { children: [_jsx("th", { className: "px-4 py-3 text-left", children: "Role" }), _jsx("th", { className: "px-4 py-3 text-left", children: "Company" }), _jsx("th", { className: "px-4 py-3 text-left", children: "Location" }), _jsx("th", { className: "px-4 py-3 text-left", children: "Posted" })] }) }), _jsxs("tbody", { className: "divide-y divide-terminal-green/15 text-terminal-green/80", children: [isLoading && listings.length === 0 ? (_jsx("tr", { children: _jsx("td", { colSpan: 4, className: "px-4 py-6 text-center text-xs uppercase tracking-[0.3em] text-terminal-green/50", children: "Scanning boards\uFFFD" }) })) : null, listings.map((job) => (_jsxs("tr", { className: "hover:bg-terminal-green/10", children: [_jsx("td", { className: "px-4 py-3", children: _jsx("a", { href: job.url, target: "_blank", rel: "noreferrer", className: "text-terminal-green hover:text-terminal-green/80", children: job.title }) }), _jsx("td", { className: "px-4 py-3 text-terminal-green/60", children: job.company }), _jsx("td", { className: "px-4 py-3 text-terminal-green/60", children: job.remote ? `${job.location} - remote` : job.location }), _jsx("td", { className: "px-4 py-3 text-terminal-green/50", children: job.postedAt ? formatRelativeTime(job.postedAt) : 'recent' })] }, job.id)))] })] }) })] }));
}
function CommunitiesPanel({ communities, memberships, }) {
    const { posts, isLoading, error, lastUpdated } = communities;
    const membershipIds = new Set(memberships.map((membership) => membership.id));
    const filtered = membershipIds.size ? posts.filter((post) => membershipIds.has(post.forum)) : posts;
    const visiblePosts = filtered.length ? filtered : posts;
    return (_jsxs("div", { className: "rounded-2xl border border-terminal-green/30 bg-black/70 p-6", children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-3", children: [_jsxs("div", { className: "space-y-1", children: [_jsx("h3", { className: "text-sm uppercase tracking-[0.35em] text-terminal-green", children: "Community radar" }), memberships.length ? (_jsxs("p", { className: "text-xs text-terminal-green/45", children: ["Forums: ", memberships.map((membership) => membership.label).join(' - ')] })) : (_jsx("p", { className: "text-xs text-terminal-green/50", children: "Join a session to unlock personalized forums." }))] }), _jsx("span", { className: "text-[11px] uppercase tracking-[0.3em] text-terminal-green/40", children: lastUpdated ? `Updated ${formatRelativeTime(lastUpdated)}` : `${visiblePosts.length} threads` })] }), error ? (_jsxs("div", { className: "mt-4 flex items-center gap-3 rounded-lg border border-terminal-green/40 bg-terminal-green/10 p-3 text-xs text-amber-300", children: [_jsx(AlertTriangle, { className: "h-4 w-4" }), _jsx("span", { children: error })] })) : null, _jsxs("div", { className: "mt-4 grid gap-4 md:grid-cols-2", children: [isLoading && visiblePosts.length === 0 ? (_jsx("div", { className: "col-span-full grid h-32 place-items-center text-xs uppercase tracking-[0.3em] text-terminal-green/50", children: "Listening\uFFFD" })) : null, visiblePosts.map((post) => (_jsxs("a", { href: post.url, target: "_blank", rel: "noreferrer", className: "group flex flex-col gap-3 rounded-xl border border-terminal-green/30 bg-black/60 p-4 transition hover:border-terminal-green/60 hover:bg-black/70", children: [_jsxs("div", { className: "flex items-center justify-between text-[11px] uppercase tracking-[0.3em] text-terminal-green/45", children: [_jsx("span", { children: post.forumLabel }), _jsx("span", { children: post.createdAt ? formatRelativeTime(post.createdAt) : 'today' })] }), _jsx("h4", { className: "text-sm text-terminal-green group-hover:text-terminal-green/80", children: post.title }), _jsxs("div", { className: "flex items-center gap-4 text-xs text-terminal-green/50", children: [_jsxs("span", { children: ["? ", formatCompactNumber(post.score)] }), _jsxs("span", { children: ["?? ", formatCompactNumber(post.comments)] }), _jsxs("span", { children: ["by ", post.author] })] })] }, post.id)))] })] }));
}
function CertificatesPanel({ certificates }) {
    const { programs, isLoading, error, lastUpdated } = certificates;
    return (_jsxs("div", { className: "rounded-2xl border border-terminal-green/30 bg-black/70 p-6", children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-3", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-sm uppercase tracking-[0.35em] text-terminal-green", children: "Certificate deck" }), _jsx("p", { className: "text-xs text-terminal-green/50", children: "Financegram-curated upskilling for coverage teams." })] }), _jsx("span", { className: "text-[11px] uppercase tracking-[0.3em] text-terminal-green/40", children: lastUpdated ? `Validated ${formatRelativeTime(lastUpdated)}` : `${programs.length} programs` })] }), error ? (_jsxs("div", { className: "mt-4 flex items-center gap-3 rounded-lg border border-terminal-green/40 bg-terminal-green/10 p-3 text-xs text-amber-300", children: [_jsx(AlertTriangle, { className: "h-4 w-4" }), _jsx("span", { children: error })] })) : null, _jsxs("div", { className: "mt-6 grid gap-4 md:grid-cols-2", children: [isLoading && programs.length === 0 ? (_jsx("div", { className: "col-span-full grid h-32 place-items-center text-xs uppercase tracking-[0.3em] text-terminal-green/50", children: "Loading catalogue\uFFFD" })) : null, programs.map((program) => (_jsxs("div", { className: "flex flex-col gap-4 rounded-xl border border-terminal-green/30 bg-black/60 p-4", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "h-12 w-12 overflow-hidden rounded border border-terminal-green/30 bg-terminal-green/10", children: program.imageUrl ? (_jsx("img", { src: program.imageUrl, alt: program.provider, className: "h-full w-full object-contain", loading: "lazy" })) : (_jsx("div", { className: "grid h-full w-full place-items-center text-[10px] uppercase tracking-[0.3em] text-terminal-green/40", children: "no art" })) }), _jsxs("div", { children: [_jsx("h4", { className: "text-sm text-terminal-green", children: program.title }), _jsx("p", { className: "text-xs uppercase tracking-[0.3em] text-terminal-green/50", children: program.provider })] })] }), _jsx("p", { className: "text-xs text-terminal-green/60", children: program.description }), _jsxs("ul", { className: "space-y-1 text-xs text-terminal-green/45", children: [_jsxs("li", { children: ["Duration - ", program.duration] }), _jsxs("li", { children: ["Format - ", program.format] }), _jsxs("li", { children: ["Cost - ", program.costRange] })] }), _jsx("div", { children: _jsxs("a", { href: program.url, target: "_blank", rel: "noreferrer", className: "inline-flex items-center gap-2 text-xs uppercase tracking-[0.3em] text-terminal-green hover:text-terminal-green/80", children: ["Explore", _jsx(BadgeCheck, { className: "h-4 w-4" })] }) })] }, program.id)))] })] }));
}
function TvPanel() {
    return (_jsxs("div", { className: "rounded-2xl border border-terminal-green/30 bg-black/70 p-6", children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-3", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-sm uppercase tracking-[0.35em] text-terminal-green", children: "Live feeds" }), _jsx("p", { className: "text-xs text-terminal-green/50", children: "Financegram rotations plus Bloomberg\uFFFDs public desk coverage." })] }), _jsx("span", { className: "text-[11px] uppercase tracking-[0.3em] text-terminal-green/40", children: "External streams" })] }), _jsxs("div", { className: "mt-4 grid gap-4 lg:grid-cols-2", children: [_jsx("iframe", { className: "aspect-video w-full rounded-xl border border-terminal-green/30", src: "https://www.youtube.com/embed/dp8PhLsUcFE?rel=0&showinfo=0", allow: "accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture", allowFullScreen: true, title: "Bloomberg Global News" }), _jsx("iframe", { className: "aspect-video w-full rounded-xl border border-terminal-green/30", src: "https://www.youtube.com/embed/EzQ57sVQ9xw?rel=0&showinfo=0", allow: "accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture", allowFullScreen: true, title: "Bloomberg Quicktake" })] }), _jsx("p", { className: "mt-3 text-xs text-terminal-green/45", children: "Streams open in-place. Audio defaults muted\uFFFDenable sound per panel to comply with workspace policy." })] }));
}
function MarketPulseCard({ data }) {
    const top = data.performanceSummary?.leaders ?? [];
    const bottom = data.performanceSummary?.laggards ?? [];
    return (_jsxs("div", { className: "rounded-2xl border border-terminal-green/30 bg-black/70 p-5", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("h4", { className: "text-xs uppercase tracking-[0.35em] text-terminal-green", children: "Market pulse" }), _jsx("span", { className: "text-[11px] uppercase tracking-[0.3em] text-terminal-green/40", children: data.lastUpdated ? formatRelativeTime(data.lastUpdated) : 'awaiting data' })] }), _jsxs("div", { className: "mt-4 space-y-4 text-xs", children: [_jsxs("div", { children: [_jsx("p", { className: "uppercase tracking-[0.3em] text-terminal-green/50", children: "Leaders" }), _jsx("div", { className: "mt-2 space-y-2", children: top.length === 0 ? (_jsx("p", { className: "text-terminal-green/40", children: "Waiting for market data." })) : (top.map((item) => (_jsxs("div", { className: "flex items-center justify-between text-terminal-green", children: [_jsxs("span", { children: [item.symbol, _jsxs("span", { className: "text-terminal-green/40", children: [" - ", item.label] })] }), _jsx("span", { className: "text-terminal-green", children: formatPercent(item.changePercent) })] }, item.symbol)))) })] }), _jsxs("div", { children: [_jsx("p", { className: "uppercase tracking-[0.3em] text-terminal-green/50", children: "Laggards" }), _jsx("div", { className: "mt-2 space-y-2", children: bottom.length === 0 ? (_jsx("p", { className: "text-terminal-green/40", children: "No decliners yet." })) : (bottom.map((item) => (_jsxs("div", { className: "flex items-center justify-between text-terminal-green", children: [_jsxs("span", { children: [item.symbol, _jsxs("span", { className: "text-terminal-green/40", children: [" - ", item.label] })] }), _jsx("span", { className: "text-rose-400", children: formatPercent(item.changePercent) })] }, item.symbol)))) })] })] })] }));
}
function HeadlineTicker({ news }) {
    return (_jsxs("div", { className: "rounded-2xl border border-terminal-green/30 bg-black/70 p-5", children: [_jsx("h4", { className: "text-xs uppercase tracking-[0.35em] text-terminal-green", children: "Headline ticker" }), _jsxs("div", { className: "mt-3 space-y-3 text-xs text-terminal-green/60", children: [news.items.slice(0, 5).map((item) => (_jsxs("a", { href: item.url, target: "_blank", rel: "noreferrer", className: "flex items-center justify-between gap-3 border-b border-terminal-green/20 pb-2 last:border-b-0 hover:text-terminal-green", children: [_jsx("span", { className: "line-clamp-2", children: item.title }), _jsx("span", { className: "text-terminal-green/40", children: item.publishedAt ? formatRelativeTime(item.publishedAt) : 'now' })] }, item.id))), news.items.length === 0 ? (_jsx("p", { className: "text-terminal-green/40", children: "No headlines loaded yet." })) : null] })] }));
}
function SessionCard({ session, onLogout, onLogin, onDemo, isAuthenticating, }) {
    return (_jsxs("div", { className: "rounded-2xl border border-terminal-green/30 bg-black/70 p-5", children: [_jsx("h4", { className: "text-xs uppercase tracking-[0.35em] text-terminal-green", children: "Account" }), session ? (_jsxs("div", { className: "mt-3 space-y-3 text-sm text-terminal-green", children: [_jsxs("div", { className: "space-y-1", children: [_jsx("p", { className: "text-terminal-green/70", children: "Logged in as" }), _jsx("p", { className: "text-lg text-terminal-green", children: session.name }), _jsx("p", { className: "text-xs uppercase tracking-[0.3em] text-terminal-green/40", children: session.email })] }), session.communities.length ? (_jsxs("div", { className: "space-y-1 text-xs text-terminal-green/55", children: [_jsx("p", { className: "uppercase tracking-[0.3em] text-terminal-green/50", children: "Forums" }), _jsx("ul", { className: "space-y-1", children: session.communities.map((membership) => (_jsx("li", { children: membership.label }, membership.id))) })] })) : null, _jsx(Button, { variant: "ghost", className: "w-full border border-terminal-green/30 bg-terminal-green/10 text-terminal-green hover:bg-terminal-green/20", onClick: () => {
                            void onLogout();
                        }, children: "Sign out" })] })) : (_jsxs("div", { className: "mt-3 space-y-3 text-sm text-terminal-green/70", children: [_jsx("p", { children: "Authenticate to personalize the terminal and unlock watchlists." }), _jsx(Button, { className: "w-full bg-terminal-green text-black hover:bg-terminal-green/80", onClick: onLogin, disabled: isAuthenticating, children: "Email login" }), _jsx(Button, { variant: "ghost", className: "w-full border border-terminal-green/30 bg-terminal-green/10 text-terminal-green hover:bg-terminal-green/20", onClick: () => {
                            void onDemo();
                        }, disabled: isAuthenticating, children: "Launch LinkedIn demo session" })] }))] }));
}
export default TerminalDashboard;
